### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by a912289748** [hustvl/Vim#42]

**Comment by Weishangbin** [comment]
> _No description provided._

你好请问你解决这个问题了吗

**Comment by IamShubhamGupto** [comment]
Could you provide the full error message? I had the same issue and it because `triton` was compiled with a different CUDA version compared to `mamba_ssm`

Compiling both from scratch on my device solved the issue

**Comment by ZXXaaaa** [comment]
> Could you provide the full error message? I had the same issue and it because `triton` was compiled with a different CUDA version compared to `mamba_ssm`
> 
> Compiling both from scratch on my device solved the issue

this is my error
CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
Can you help me? thx

**Comment by ZXXaaaa** [comment]
> > _No description provided._
> 
> 你好请问你解决这个问题了吗

Have you solved it?

**Comment by zjy-2020** [comment]
> > Could you provide the full error message? I had the same issue and it because `triton` was compiled with a different CUDA version compared to `mamba_ssm`
> > Compiling both from scratch on my device solved the issue
> 
> this is my error CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Can you help me? thx

Hello, I have encountered the same problem, have you solved it?

**Comment by zjy-2020** [comment]
> 你能提供完整的错误消息吗？我遇到了同样的问题，因为与`triton``mamba_ssm`
> 
> 在我的设备上从头开始编译两者解决了这个问题
Hello, I have encountered the same problem, have you solved it?

**Comment by ZXXaaaa** [comment]
> > > Could you provide the full error message? I had the same issue and it because `triton` was compiled with a different CUDA version compared to `mamba_ssm`
> > > Compiling both from scratch on my device solved the issue
> > 
> > 
> > this is my error CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. Can you help me? thx
> 
> Hello, I have encountered the same problem, have you solved it?

Yes, I solved it by rented a more powerful server with better GPU

**Comment by ganyang0720** [comment]
Regarding the computing power of NVIDIA graphics cards, the minimum requirement is 70
