### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### ISSUE THREAD

**Issue by ZXXaaaa** [hustvl/Vim#74]
CUDA error: no kernel image is available for execution on the device
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Have you ever encountered this problem?

**Comment by perisage** [comment]
same issue, how did you solved it? Thanks!

**Comment by ZXXaaaa** [comment]
I solved it by renting a more powerful server with better GPU

**Comment by perisage** [comment]
Thanks, i'll try it!
